site_name: startorch
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - get_started.md
  - User Guide:
      #      - quickstart.md
      - sequence.md
  - Reference:
      - example: refs/example.md
      - periodic: refs/periodic.md
      - plot: refs/plot.md
      - random: refs/random.md
      - sequence: refs/sequence.md
      - tensor: refs/tensor.md
      - timeseries: refs/timeseries.md
      - transformer: refs/transformer.md
      - transition: refs/transition.md
      - utils: refs/utils.md
  - GitHub: https://github.com/durandtibo/startorch

repo_url: https://github.com/durandtibo/startorch
repo_name: durandtibo/startorch

markdown_extensions:
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ ../src ]
          options:
            allow_inspection: true
            docstring_style: google
            separate_signature: true
            show_bases: true
            show_object_full_path: true
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true

extra:
  version:
    method: mike

copyright: Copyright &copy; 2023 - present Thibaut Durand
